language: node_js
node_js:
  - "node"
services:
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6
      - postgresql-client-9.6
before_install:
  - npm install -g standard
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE testing_db;' -U postgres
  - psql -c 'CREATE USER foo WITH PASSWORD 'bar';' -U postgres
  - psql --dbname=testing_db --file=sql/create-tables.sql
test:
  adapter: postgresql
  database: testing_db